
language: generic

env:
  global:
    - secure: "NArKc/MxyQCWqQcnh+qx1rPyw3te01bC8kqbMwKUyOsJNuL9faS+6VnplKhfk7Ck5xAMG5Qvta4CZvCO9lCM1q18Ntfs4KFjmoIlFpRycJqYVM8Lw8mnxGpOEdlVIFi+eWDRAfpEBKjdRnvsnnxnDFo0ROEjfmSrbi47/8h62EcWtTpEUmpLfRVZyUuUOZ4zYXV65ZDVhLWBt5zQWlYOl9CnTI4p8ktf0TffZxFKuhL6xrbEZtLhSfEkfecoWYEJ7luOxixJny3MEeW8LS4MKRA4naVwNk+lNL5yKHgMnz05r5pINXVshUsYcbbWs/odUOwwZDiV/8RMHfht1b+HHrxL8KenSbj4t8NvbgHqEB1wJbrTt3dmZTez5gxnk7g2MYSpSZJHauKQQD5fVR4paSsVEgOioZcL6ZPs8pacXEQ1T3vKd9jhLeQbJppeTR1hvny3N/rnMym2GYVL69a/eIMCoTKPZjTi0l5Ki3jhQOTnmQZJm0NASBA7Vp2f0pZBrOj92bHRkhcNu6wEY1Gzv1+3pDBJLHbp3szQzAiT5eMjoYC5wtcDdTq93jdEXhObhNUUOMOcOzEho+PZSuGrZCa7cjN0WAicQuv1wtXHhdwm5ITEnG7yGSUBfmfDoFFu5P0SkzA6n5v9YfICTQ5zvNX4tcc3dNou8y6xPl4vPsY="
    - 'deployable="^(master|dev|travis)$"'
    - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
    - QT_API=pyside
  matrix:
    - PYTHON=2.6 DEPS="minimal"
    - PYTHON=2.7 DEPS="" FLAKE=1 DEPLOY_DOCS=1
    - PYTHON=3.3 DEPS=""
    # - PYTHON=3.4 DEPS=full  # is this necessary if 3.3 and 3.5 are tested?
    - PYTHON=3.5 DEPS="" FLAKE=1

git:
  submodules: false

sudo: false

addons:
  apt:
    packages:
    - gfortran

# cache:
#   directories:
#     - $HOME/miniconda
#     - $HOME/mycache

before_install:
  ## First off, let's lint the version numbers in __init__.py and Changes.md

  # before we build, check to see if we're in a release branch, and if
  # so, then do some 0th order validation on the viscid.__version__
  - 'if [[ ($TRAVIS_BRANCH =~ ^(.*release.*|master)$) ]]; then
       if [ "$(grep __version__ viscid/__init__.py | grep -E "(dev|travis)")" != "" ]; then
         echo "Oops, you are preparing a release, but you still have either";
         echo "dev or travis in the version number";
         false;
       fi
     elif [[ $TRAVIS_BRANCH =~ ${deployable} ]]; then
       if [ "$(grep __version__ viscid/__init__.py | grep ${TRAVIS_BRANCH} )" == "" ]; then
         echo "Oops, You are on a deployable branch (that is not master), ";
         echo "but the branch name is not in the version number";
         false;
       fi
     fi'

  # make sure the version string appears in CHANGES.md
  - 'ver_re="__version__.*[\"'']+([^\"'']+)[\"'']+"'
  - 'version=$([[ "$(grep __version__ viscid/__init__.py)" =~ ${ver_re} ]]; echo "${BASH_REMATCH[1]}")'
  - 'if [ "$(grep -E "${version}\s*$" CHANGES.md)" == "" ]; then
       echo "Oops, the version ${version} does not appear in CHANGES.md";
       false;
     fi'

  ## Now setup the Anaconda tools
  # it saves some download time to use the same python iff 2.7
  - 'if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
       export CONDA_URL="https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh";
     else
       export CONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh";
     fi'
  # linux has wget, OS X has curl... such is life
  - 'if [[ "$(which wget &>/dev/null && echo $?)" == "0" ]]; then
       wget "${CONDA_URL}" -O miniconda.sh;
     else
       curl "${CONDA_URL}" > miniconda.sh;
     fi'
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  ## Now setup some Viscid specific things, like rc files and make sure
  ## we have a virtual frame buffer
  - mkdir -p ~/.config/matplotlib
  - cp resources/matplotlibrc ~/.config/matplotlib/
  - cp resources/viscidrc ~/.viscidrc
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - mkdir -p ${HOME}/mycache
  - 'export env_name="viscid${PYTHON/./}${DEPS}"'
  - 'export envpath="$HOME/miniconda/envs/${env_name}"'
  - 'export env_spec="resources/${env_name}.yml"'
  - 'export cached_env_spec="${HOME}/mycache/${env_name}.yml"'
  - 'export prefix="${HOME}/inst/${env_name}"'

  - ls ../Viscid/${env_spec}
  - mkdir -p $HOME/miniconda/envs
  - ls $HOME/miniconda/envs

  # if conda package list doesn't match the cached one, just blast
  # the cached conda environment
  - 'if [ -f ${cached_env_spec} ]; then
       if [ "$(diff -qw ${env_spec} ${cached_env_spec})" != "" ]; then
         echo "Package Lists Differed, killing current venv";
         echo "$(diff -w ${env_spec} ${cached_env_spec})";
         rm ${cached_env_spec};
         rm -rf ${envpath};
       fi
     fi'

  # if the conda envronment we need isn't cached, create it, otherwise
  # do an update
  - 'if [ ! -d "${envpath}" ]; then
       conda env create -f ${env_spec};
       source activate ${env_name};
       cp ${env_spec} ${cached_env_spec};
     else
       source activate ${env_name};
       conda update --all --yes;
     fi'

  # if deplying docs, run tests inplace, this makes preparing the docs
  # faster since cython's fused types makes 8 times too much code, ug!
  - 'if [ "${DEPLOY_DOCS}" == "1" ]; then
       make inplace;
       export PATH="${PWD}/scripts:${PATH}";
       export PYTHONPATH="${PWD}:${PYTHONPATH}";
     else
       rm -rf ${prefix};
       python setup.py install --prefix=${prefix} --install-lib=${prefix};
       export PATH="${prefix}/bin:${PATH}";
       export PYTHONPATH="${prefix}:${PYTHONPATH}";
     fi'

before_script:
  - 'if [ "${FLAKE}" == "1" ]; then make flake8; fi'

script:
  - 'if [ "${DEPLOY_DOCS}" == "1" ]; then
       make check;
     else
       make instcheck;
     fi'
  - 'if [[ $TRAVIS_BRANCH =~ ${deployable}$ && -n "$GH_TOKEN" ]]; then
       make deploy-summary;
     fi'

deploy:
  provider: "script"
  skip_cleanup: true
  script:
    - make deploy-html
  on:
    branch: "*"
    condition: '($TRAVIS_BRANCH =~ ${deployable}) && -n "$GH_TOKEN" && ("${DEPLOY_DOCS}" == "1")'
